query PrsWithCiStatusInternal($query: String!) {
  search(query: $query, type: ISSUE, first: 100) {
    nodes {
      __typename # required for the type generator
      ... on PullRequest {
        id
        number
        url
        title
        headRefName
        headRefOid
        isDraft
        merged
        isInMergeQueue
        autoMergeRequest {
          enabledAt
        }
        statusCheckRollup {
          state
        }
      }
    }
  }
}
