[package]
name = "jj-gh"
version = "0.3.1"
edition = "2024"
description = "Manage GitHub PR Stacks natively with `jj`"
repository = "https://github.com/mrjones2014/jj-gh"
license = "MIT"
include = [
  "/Cargo.lock",
  "/Cargo.toml",
  "/LICENSE",
  "/README.md",
  # this isn't technically needed for the rust crate,
  # but I want release-plz to include changes to it
  # in the CHANGELOG.md
  "/nix/hm-module.nix",
  "/src/**/*.gql",
  "/src/**/*.rs",
  "/src/gh/github.graphql",
]

[workspace]
members = ["tools/gen-docs", "tools/gen-manpage", "tools/jj-gh-config-derive"]

[workspace.dependencies]
clap = "4"

[dependencies]
anstyle = "1"
anyhow = "1"
clap = { workspace = true, features = ["derive", "wrap_help"] }
clap_complete = "4"
clap_complete_nushell = "4"
crossterm = "0.29"
figment = { version = "0.10", features = ["toml"] }
flexi_logger = { version = "0.31", default-features = false, features = [
  "colors",
] }
futures = "0.3"
gix = { version = "0.87", default-features = false, features = [
  "basic",
  "blocking-http-transport-reqwest-native-tls",
  "blocking-network-client",
  "comfort",
  "credentials",
  "max-performance-safe",
  "sha1",
] }
graphql_client = "0.16"
http = "1"
jj-gh-config-derive = { path = "tools/jj-gh-config-derive", version = "0.1.5" }
log = "0.4"
# see: https://github.com/dependabot/dependabot-core/issues/14196
noyalib = "0.0"
octocrab = "0.54"
schemars = "1"
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shell-words = "1"
supports-hyperlinks = "3.2.0"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["macros", "process", "rt", "time"] }
toml = "1"
url = "2"

[lints.clippy]
allow_attributes = "deny"
pedantic = { level = "deny", priority = -1 }

[profile.release]
strip = "symbols"
