mutation EnableAutoMerge($prId: ID!, $method: PullRequestMergeMethod!) {
  enablePullRequestAutoMerge(
    input: {
      pullRequestId: $prId,
      mergeMethod: $method
    }
  ) {
    pullRequest {
      id
    }
  }
}
