mutation EnableAutoMerge($pr_id: ID!, $method: PullRequestMergeMethod!) {
  enablePullRequestAutoMerge(
    input: { pullRequestId: $pr_id, mergeMethod: $method }
  ) {
    pullRequest {
      id
    }
  }
}
