[package]
name = "jj-gh-config-derive"
version = "0.1.5"
edition = "2024"
description = "You are probably looking for the `jj-gh` crate instead."
repository = "https://github.com/mrjones2014/jj-gh"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["extra-traits", "full"] }

[lints.clippy]
allow_attributes = "deny"
pedantic = { level = "deny", priority = -1 }
