name: ci
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [jj-gh, clippy, nextest, treefmt, ast-grep, graphql-validate, hm-module-schema, docs, release-plz-patched]
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: jj-gh
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix build .#checks.x86_64-linux.${{ matrix.target }} --print-build-logs
      - if: matrix.target == 'jj-gh' && github.event_name == 'push'
        run: nix build .#checks.x86_64-linux.release-plz-patched --print-build-logs
      # we don't really ever need to rebuild this, so pin it in cachix
      - if: matrix.target == 'release-plz-patched' && github.event_name == 'push'
        run: |
          path=$(nix build .#checks.x86_64-linux.release-plz-patched --print-out-paths --no-link)
          cachix pin jj-gh release-plz-patched "$path"
  flake-check:
    needs: check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.check.result, 'failure') || contains(needs.check.result, 'cancelled') }}
        run: exit 1
  udeps:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: jj-gh
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix build .#udeps --print-build-logs
  release-plz:
    needs: [flake-check, udeps]
    if: ${{ github.repository_owner == 'mrjones2014' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
      id-token: write
    concurrency:
      group: release-plz
      cancel-in-progress: false
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: jj-gh
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix run .#release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_GITHUB_TOKEN }}
