name: release-plz
permissions:
  pull-requests: write
  contents: write
  issues: write
  id-token: write
on:
  workflow_run:
    workflows: [ci]
    branches: [master]
    types: [completed]
  workflow_dispatch:
concurrency:
  group: release-plz
  cancel-in-progress: false
jobs:
  release-plz:
    if: ${{ github.repository_owner == 'mrjones2014' && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock', '**/*.nix', 'rust-toolchain.toml', 'Cargo.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          save: false
      - run: nix run .#release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_GITHUB_TOKEN }}
