name: Update flake dependencies
on:
  schedule:
    - cron: '0 16 * * 5'
  workflow_dispatch: # for allowing manual triggers of the workflow
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: bump github-graphql-schema tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          latest=$(gh api repos/octokit/graphql-schema/releases/latest --jq .tag_name)
          sed -i -E "s|(github:octokit/graphql-schema/)v[0-9]+\.[0-9]+\.[0-9]+|\1${latest}|" flake.nix
      - name: update flake.lock
        run: nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "flake: update dependencies"
          title: "[automation] update flake dependencies"
          branch: "automation/update-flake-dependencies"
