name: Update GitHub GraphQL schema
on:
  schedule:
    - cron: '0 16 * * 5'
  workflow_dispatch:
jobs:
  update-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: update GitHub GraphQL schema
        run: nix run .#fetch-schema
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(dpes): update GitHub GraphQL schema"
          title: "chore(deps): update GitHub GraphQL schema"
          branch: "automation/update-graphql-schema"
