//! Print Clap-derived Markdown reference for `jj-gh` to stdout. The wrapper
//! shell app `apps.docs` in `flake.nix` pipes this through the project
//! formatter and writes/diffs `DOCS.md`.

use jj_gh::Cli;

const DOCS_BANNER: &str =
    "<!-- Generated by tools/gen-docs. Do not edit by hand. Run `nix run .#docs`. -->\n\n";

fn main() {
    print!("{DOCS_BANNER}{}", clap_markdown::help_markdown::<Cli>());
}
